ALTER TABLE companies ADD COLUMN IF NOT EXISTS email TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS senha TEXT;

ALTER TABLE sellers ADD COLUMN IF NOT EXISTS marcas_liberadas TEXT[] DEFAULT '{}';
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS marcas_bloqueadas TEXT[] DEFAULT '{}';
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS comissao_por_marca JSONB DEFAULT '{}';
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES auth.users(id);
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS senha TEXT;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS codigo_cliente TEXT;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS codigo_vinculo TEXT;
ALTER TABLE sellers ADD COLUMN IF NOT EXISTS ativo BOOLEAN DEFAULT TRUE;

ALTER TABLE customers ADD COLUMN IF NOT EXISTS nome_empresa TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS whatsapp TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS endereco TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS cidade TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS estado TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS cep TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS vendedor_marcas_bloqueadas TEXT[] DEFAULT '{}';
ALTER TABLE customers ADD COLUMN IF NOT EXISTS senha TEXT;
ALTER TABLE customers ADD COLUMN IF NOT EXISTS codigo_acesso TEXT;
